### ISSUE TITLE
任务列表

### ISSUE THREAD

**Issue by ZhangHanDong** [rust-lang-cn/www.rust-lang.org#2]
这里是任务列表分发，陆续发布

- [x] cli #22 @b41sh *
- [x] code-of-conduct #25 @b41sh *
- [x] common #6 @Hexilee *
- [x] governance #7 @NOVA-ME *
- [x] homepage #5 @aaranxu *
- [x] learn #3 @OlingCat *
- [x] licenses #35 @b41sh *
- [x] media-guide #33 @OlingCat *
- [x] policies #31  @b41sh *
- [x] security #29 @starccy *
- [x] teams #9 @readlnh *
- [x] tools #8 @huangjj27 *
- [x] install #4 @0kaguya *，merged into Tools

新增部分：
- [x] 404 #43 @OlingCat *
- [x] community.ftl #53 @zuoxinyu *
- [x] embedded.ftl #47 @ZhangHanDong *
- [x] networking #40 @b41sh *
- [x] production #55 @b41 *
- [x] wasm #42 @OlingCat *

本次贡献者分工角色和工作流程记录：

![image](https://user-images.githubusercontent.com/27893/59253190-42625380-8c60-11e9-9e8c-85d5b230f65c.png)

**Comment by ZhangHanDong** [comment]
说明：

目前有些内容是写死到templates模板页面里的，比如policies，而没有独立的locales/zh-CN下的ftl文件，这些放到后面再看如何处理。需要 @Aimeedeer 帮忙问一下，是否可以把那么模板里的内容猜出独立的ftl文件再翻译，还是说等官方拆解？

有ftl文件的内容，认领的就可以开始翻译了。

**Comment by OlingCat** [comment]
后面标有 * 号的已全部迁移至 Pontoon
